name: CloudDefense AI Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

     
      - name: Run CloudDefense AI scan
        env:
          CLOUDDEFENSE_KEY: ${{ secrets.API_KEY }}
        run: |
          curl -X POST -H "Authorization: Bearer $CLOUDDEFENSE_KEY" https://api.clouddefense.ai/v2/scan

      - name: Run tests
        run: echo "hello"
