# This is a basic workflow to help you get started with Actions

name: test

# Controls when the workflow will run

on: push
jobs:
  security:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@main
    - name: Run Cloud Defense to check for vulnerabilities
      uses: cdefense/actions/node@master
      with:
        project-name: clouddefence-1
        api-key: 38d3f8b4-9f60-4f3d-964f-83c67f61dd87
  

 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel


    # Steps represent a sequence of tasks that will be executed as part of the job
  
     
